### ISSUE TITLE
Please tag releases in git

### ISSUE THREAD

**Issue by jonassmedegaard** [moll/js-standard-error#3]
It eases tracking for some types of distribution (e.g. Debian packaging which I do) when module releases are tagged in git.

Please consider tagging releases.

**Comment by moll** [comment]
Hey! I believe I already do tag versions, don't I? Seems so from https://github.com/moll/js-standard-error/tags at least.

**Comment by jonassmedegaard** [comment]
hmm, odd!

Yes indeed. I thought I triple-checked, but must've been something at my end.  Sorry for the noise.

Oh, and now I have your attention: Thanks for writing this code, and choosing to license it freely!

**Comment by jonassmedegaard** [comment]
...aaaand push the right button this time.

**Comment by moll** [comment]
You're welcome! What are you packaging that depends on StandardError.js if I may ask?

**Comment by jonassmedegaard** [comment]
You may certainly ask :-)

I am packaging semantic web projects, including solid-server <- solid-auth-client <- @solid/oidc-rp <- standard-http-error <- standard-error
<https://wiki.debian.org/Javascript/Nodejs/Tasks/solid-server>

**Comment by moll** [comment]
Packaging each JavaScript module as a separate Debian package? Impressive feat. :P 
It's not rare for a single project to use two different [major] versions of a single module through nested dependencies. Have you come across that?

**Comment by jonassmedegaard** [comment]
It is indeed quite a task to align the different packaging models of the Node.js and Debian environments.

I have not yet personally come across cases of multiple versions needed for one stack of code. Yet...

I notice your choice of using Makefiles, and appreciate (both that and) your careful emphasis on varying _major_ versions in the kind of complication you point at: Debian approach to (what in Node.js context with semantic versioning scheme is called) multiple major versions is to then track each major version separately - e.g. by adding the major version number at the end of the Debian package name (and then having the trouble locally in Debian of correlating Debian package names with NPM package names).  Because of the headaches of that - and the likelihood of the earlier versions getting less attention - we try to track only one branch of each code project.

Most notable case I am aware of that we do track multiple concurrent versions in jQuery. And the horror of that one in particular is that we don't yet have all build tools packaged so cannot run the testsuite.  And most consumers of the jQuery packages don't provide a testsuite at all.  So there is likely a whole lot of code in Debian silently broken :-/

**Comment by jonassmedegaard** [comment]
...also no, we won't always package NPM modules as separates packages in Debian: Debian packaging involve more metadata, so tiny NPM modules gets bundled together.

For me personally, this is first time I need to bundle NPM modules - your two modules bundled as addons to their (for now, at least) only consumer, @solid/oidc-rp

**Comment by moll** [comment]
I'm glad you're a fan of Makefiles too. Did you run the tests for some reason that made you notice it in the first place? 

I figured naming the package after the major version would be a reasonable solution. As for coming across multiple major versions in a single parent project, I suspect utility libraries are likely to be the first sightings. Lodash, for a concrete example, has all of its utility functions available as separate packages. However, and I don't recall whether it started with v3 or v4, they're nowadays so bloated that a single-function comes in a thousand to few thousand line file.

```sh
$ wc node_modules/lodash.map/index.js
 2366  9191 64077 node_modules/lodash.map/index.js
```

While I usually inline a few-line custom reimplementation of various utilities, should I need a Lodash-version, I usually go with its years-old v2 modules. Having said that, bundling utility libraries with their parent is a decent way to side-step the version proliferation.

**Comment by jonassmedegaard** [comment]
Quoting Andri Möll (2019-02-03 20:08:34)
> I'm glad you're a fan of Makefiles too.

I sure am.  You must be a greybeard: It is quite a while since I last 
saw the ancient joke of "make love" - first I recall seeing it was for 
the UW-imap daemon, where it would emit "not war?" :-)

In Debian, the "spine" of packaging - i.e. the equivalent of 
"package.json" for Node.js modules - is debian/rules which must be a 
make file.

I am (contrary to most Debian developers, I suspect) quite fond of the 
make language.


> Did you run the tests for some reason that made you notice it in the 
> first place?

I look closely at build routines of each module, to consider of sensible 
to rely on those or mimick using different tools e.g. more modern or 
(less modern but) available at all in Debian.


[...]
> bundling utility libraries with their parent is a decent way to 
> side-step the version proliferation.

Bundling is generally frowned upon in Debian. Prime argument why is the 
headache of tracking security bugs when code exist in multiple locations 
some identical, some identical but embedded, and some derived.

I find it problematic (a step backwards) that Debian in recent times 
(since a couple years only) require bundling for tiny JavaScript modules 
specifically, while at the same tile discourage upstreams doing same, 
and Debian doing same for other projects.


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by moll** [comment]
While we're on the topic of versioning, what's your take on the Nix philosophy of permitting parallel versions of everything by default? The Mac's (and now on Linux) Homebrew package manager follows the same path. I for one, as a developer, am not too keen on the insistence that only a single (major or not) version be installed at any time. I'm often come across the need to debug or test on older patch versions and `su`ing to manually install an older .dpkg or equivalent (if it even runs because it may depend on older versions of older libraries) is not a great workflow.

**Comment by jonassmedegaard** [comment]
Quoting Andri Möll (2019-02-04 13:09:05)
> While we're on the topic of versioning, what's your take on the Nix 
> philosophy of permitting parallel versions of everything by default? 
> The Mac's (and now on Linux) Homebrew package manager follows the same 
> path. I for one, as a developer, am not too keen on the insistence 
> that only a single (major or not) version be installed at any time. 
> I'm often come across the need to debug or test on older patch 
> versions and `su`ing to manually install an older .dpkg or equivalent 
> (if it even runs because it may depend on older versions of older 
> libraries) is not a great workflow.

It sounds lovely.  But who's gonna clean up if there is no encouragement 
to get onto most possible part aligned with each other?


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private
